name: CICD prod

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # - name: Install dependencies
        # run: |
          # npm install

      - name: Build and tag Docker image for prodelopment
        run: |
          docker build -t jonasrsribeiro/nc-controller-conversor -f Dockerfile.prod .
          docker tag jonasrsribeiro/nc-controller-conversor:latest jonasrsribeiro/nc-controller-conversor:prod

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jonasrsribeiro --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonasrsribeiro/nc-controller-conversor:latest
          docker push jonasrsribeiro/nc-controller-conversor:prod